name: C/C++ CI

permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iulianojay/astrea:dev
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
    - name: https://github.com/actions/checkout/issues/1720
      run: |
        chmod -R u+rwX .

    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }} # https://github.com/actions/checkout/discussions/1637

    - name: Setup
      run: |
        echo "ASTREA_ROOT=$(pwd)" >> "$GITHUB_ENV"
        cp -r ./.conan2 ~

    - name: Build
      run: |
        make release all

    - name: Run Tests
      run: |
        make run_tests

    - name: Run Examples
      run: |
        make run_examples

  Coverage:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iulianojay/astrea:dev
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
    - name: https://github.com/actions/checkout/issues/1720
      run: |
        chmod -R u+rwX .

    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }} # https://github.com/actions/checkout/discussions/1637

    - name: Setup
      run: |
        echo "ASTREA_ROOT=$(pwd)" >> "$GITHUB_ENV"
        cp -r ./.conan2 ~

    - name: Build Debug
      run: |
        make debug all

    - name: Run Coverage
      run: |
        mkdir .gcovr
        touch .gcovr/coverage.xml
        make coverage-cobertura

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: .gcovr/coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: true
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 238a4a61ca19471caa1e39376158d625
        filename: coverage.json
        label: Hello
        message: World
        color: orange