name: C/C++ CI

permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  Build-and-Test:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iulianojay/astrea:dev
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
    - name: https://github.com/actions/checkout/issues/1720
      run: |
        chmod -R u+rwX .

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }} # https://github.com/actions/checkout/discussions/1637

    - name: Setup
      run: |
        echo "ASTREA_ROOT=$(pwd)" >> "$GITHUB_ENV"
        cp -r ./.conan2 ~

    - name: Build
      run: |
        make release all

    - name: Run Tests
      run: |
        make run_tests

    - name: Run Examples
      run: |
        make run_examples
