name: C/C++ CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iulianojay/astrea:dev
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
    - name: https://github.com/actions/checkout/issues/1720
      run: |
        chmod -R u+rwX .
    - uses: actions/checkout@v4
      with:
        path: ${{ github.sha }}
    - name: make
      run: cd $ASTREA_ROOT && make
    - name: make run_tests
      run: cd $ASTREA_ROOT && make run_tests
